/*
** NOTE: This file is generated by Gulp and should not be edited directly!
** Any changes made directly to this file will be overwritten next time its asset group is processed by Gulp.
*/

(function () {
    document.addEventListener('load', function () {
        $('.js-replace-item-checkbox').attr('checked', 'checked');
    });

    $('.js-replace-item-checkbox').attr('checked', 'checked');
})();

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInByZXZpZXcuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLEFBTEE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSIsImZpbGUiOiJwcmV2aWV3LmpzIiwic291cmNlc0NvbnRlbnQiOlsiKGZ1bmN0aW9uICgpIHtcclxuICAgIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCBmdW5jdGlvbiAoKSB7XHJcbiAgICAgICAgJCgnLmpzLXJlcGxhY2UtaXRlbS1jaGVja2JveCcpLmF0dHIoJ2NoZWNrZWQnLCAnY2hlY2tlZCcpO1xyXG4gICAgfSk7XHJcblxyXG4gICAgJCgnLmpzLXJlcGxhY2UtaXRlbS1jaGVja2JveCcpLmF0dHIoJ2NoZWNrZWQnLCAnY2hlY2tlZCcpO1xyXG59KSgpO1xyXG4iXSwic291cmNlUm9vdCI6Ii9zb3VyY2UvIn0=
